## Numpy array and basics 

In [2]:
import numpy as np

### Creating array from list

In [3]:
arr_1d = np.array([1,2,3,4,5])
print(arr_1d)

arr_2d = np.array([[1,2,3], [1,2,3]])
print(arr_2d)

[1 2 3 4 5]
[[1 2 3]
 [1 2 3]]


### Python list vs numpy array

In [4]:

py_list = [1, 2, 3, 4, 5]
print("Python list multiplication: ", py_list * 2)


np_array = np.array([1, 2, 3, 4, 5])
print("Numpy array multiplication: ", np_array * 2)


import time
start = time.time()
py_list = [i*2 for i in range(1000000)]
print("List operation time: ",time.time() - start)

start = time.time()
np_array = np.arange(1000000) * 2
print("np array opreation time: ",time.time() - start)

Python list multiplication:  [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
Numpy array multiplication:  [ 2  4  6  8 10]
List operation time:  0.06796789169311523
np array opreation time:  0.0070459842681884766


### Creating array from scratch

In [5]:
zeros = np.zeros((3,4))
print("zeros: \n", zeros)

zeros: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


### Creating array using different numpy functions

In [3]:
zeros = np.zeros((2,3))
print("zero array: \n", zeros)

ones = np.ones((3,3))
print("ones array: \n", ones)

full = np.full((4,4), 8)
print("full array: \n", full)

random = np.random.random((2,3))
print("random array: \n", random)

sequence = np.arange(0, 11, 1) #start stop steps
print("sequence array: \n", sequence)

zero array: 
 [[0. 0. 0.]
 [0. 0. 0.]]
ones array: 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
full array: 
 [[8 8 8 8]
 [8 8 8 8]
 [8 8 8 8]
 [8 8 8 8]]
random array: 
 [[0.85362863 0.7007489  0.21488691]
 [0.81838908 0.07614121 0.74272417]]
sequence array: 
 [ 0  1  2  3  4  5  6  7  8  9 10]


### Vector, Matrix and Tensor

In [ ]:
vector = np.array([1, 2, 3])            # 1-D array: vector
print("Vector: ", vector)

matrix = np.array([[1, 2, 3],           # 2-D array: matrix
                   [4, 5, 6]])
print("Matrix: ", matrix)

tensor = np.array([[[1, 2], [3, 4]],    # multy-D array: tensor
                   [[5, 6], [7, 8]]])
print("Tensor: ", tensor)

Vector:  [1 2 3]
Matrix:  [[1 2 3]
 [4 5 6]]
Tensor:  [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array Properties

In [7]:
arr = np.array([[1, 2, 3], 
                [4, 5, 6]])
print("Shape ", arr.shape)
print("Dimension ", arr.ndim)
print("Size ", arr.size)
print("DType ", arr.dtype)

Shape  (2, 3)
Dimension  2
Size  6
DType  int64


### Reshaping Array

In [ ]:
arr = np.arange(12)
print(" Original array: ", arr)

reshaped = arr.reshape((3, 4))  # give size of array inside ()
print("\n Reshaped array: ", reshaped)

# make new copy of flattened version 
flattened = reshaped.flatten()
print("\n Flattened Array: ",flattened)

# doesn't make new copy, just viewing original array in flattened version. if we change something in raveled, may change in original array (only difference in memory level)
raveled = reshaped.ravel()
print("\n Raveled array: ", raveled)

transpose = reshaped.T
print("\n Transposed array: ", transpose)

# provide duplicate value as it is
# random_arr = np.array([[1,4,5],  
#                        [1,2,3]])
# toFlatten = random_arr.flatten()   
# print(toFlatten)


 Original array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Reshaped array:  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 Flattened Array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Raveled array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Transposed array:  [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
