## Numpy Array Operation

In [2]:
import numpy as np

### Basic slicing 

In [3]:
arr = np.arange(1, 10)
print(arr)

print(arr[3])
print("with steps: ", arr[1:9:3])
print("negative index: ", arr[-2])
print()

[1 2 3 4 5 6 7 8 9]
4
with steps:  [2 5 8]
negative index:  8



In [10]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
print("first column: ", arr[:, 0])

first column:  [1 4 7]


### Sorting Array

In [15]:
unsorted = np.array([4, 3, 5, 2, 1, 1, 2, 8, 7, 6])
print("sorted array: ", np.sort(unsorted))

unsorted_2d = np.array([[1, 3],
                        [2,4],
                        [5,3]])
print("column sorted: ", np.sort(unsorted_2d, axis=0))
print("row sorted: ", np.sort(unsorted_2d, 1))
print("sort 2nd column:", np.sort(unsorted_2d[:, 1]))

sorted array:  [1 1 2 2 3 4 5 6 7 8]
column sorted:  [[1 3]
 [2 3]
 [5 4]]
row sorted:  [[1 3]
 [2 4]
 [3 5]]
sort 2nd column: [3 3 4]


### Filter

In [24]:
numbers = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
even_num = numbers[numbers%2 == 0]
print("only even: ", even_num)

# filter with mask
mask = numbers > 4
print("numbers greater than 4: ", numbers[mask])
print("value of mask: ",mask)

only even:  [ 2  4  6  8 10]
numbers greater than 4:  [ 5  6  7  8  9 10]
value of mask:  [False False False False  True  True  True  True  True  True]


### Fancy Indexing vs np.where()

In [ ]:
numbers = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
indices = [0, 3, 5, 6]
print(numbers[indices])

where_result = np.where(numbers > 4) # where this condition meets, store their indexes/indices
print("store indices: ", where_result)
print(numbers[where_result]) # those indices can be used here to take elements from array

modified_array = np.where(numbers > 5, numbers*2, numbers) # but when we give 3 argument to "np.where", it gives new modified array according to conditon
#       For each element: (condition, x, y)
#       If condition is True, return x,
#       Else return y
print(modified_array)

# if (numbers > 5):
#     numbers *2
# else:
#     numbers

# Usage | Behavior
# np.where(condition) | returns indices where condition is True 
# np.where(condition, value_if_true, value_if_false) | returns a new array applying your logic

[1 4 6 7]
store indices:  (array([4, 5, 6, 7, 8, 9]),)
[ 5  6  7  8  9 10]
[ 1  2  3  4  5 12 14 16 18 20]


### Adding and removing data

In [63]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

print(arr1 + arr2)  # add the elements 
combined_arr = np.concatenate((arr1, arr2)) # should pass arrays inside tuple
print("combined_array: ",combined_arr)  

# adding row
original_arr = np.array([[1, 4, 9], [2, 4, 6]])
new_row = np.array([2, 3, 5])  # number of column should match with original array
with_new_row = np.vstack((original_arr, new_row))

print("Original array: ",original_arr)
print("New array: ",with_new_row)

# adding new column
new_col = np.array([[100], [200]])  # number of row should match with original array
with_new_col = np.hstack((original_arr, new_col))
print("Array with new Column: ",with_new_col)


# deleting element
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
deleted1 = np.delete(arr, 0)
deleted2 = np.delete(arr, slice(0, 10, 2))
print("array after deletation: ",deleted1)
print("array after deletation: ",deleted2)

[5 7 9]
combined_array:  [1 2 3 4 5 6]
Original array:  [[1 4 9]
 [2 4 6]]
New array:  [[1 4 9]
 [2 4 6]
 [2 3 5]]
Array with new Column:  [[  1   4   9 100]
 [  2   4   6 200]]
array after deletation:  [ 2  3  4  5  6  7  8  9 10]
array after deletation:  [ 2  4  6  8 10]


### Compatibility test

In [46]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
c = np.array([9, 0, 1])

print("Compatibility shape:", a.shape == b.shape)
print("Compatibility shape:", a.shape == c.shape)

Compatibility shape: True
Compatibility shape: False
