In [2]:
import numpy as np

In [3]:
# slicing, selecting row, selecting column
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13 ,14,15]])
print(arr)

unsorted = np.array([4, 3, 5, 2, 1, 1, 2, 8, 7, 6, 10, 12])
np.sort(unsorted)
reshaped = unsorted.reshape(4, 3)
reshaped_sorted = np.sort(reshaped, axis=1)
reshaped_sorted


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


array([[ 3,  4,  5],
       [ 1,  1,  2],
       [ 2,  7,  8],
       [ 6, 10, 12]])

In [30]:
ones = np.ones((2,2))
ones2 = np.ones((2, 2))
new = np.concat((ones, ones2))
new2 = np.concatenate((ones, ones2))
new

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])